export type SeedIngredient = { key: string; name: string; qty: number; icon?: string; subType?: string };
export type SeedProfessionRecipe = {
  profession: "alchemy" | "forging" | "talisman" | "formation";
  station: "ALCHEMY_FURNACE" | "FORGE" | "TALISMAN_TABLE" | "FORMATION_ALTAR";
  rank: "APPRENTICE" | "ADEPT" | "EXPERT" | "MASTER" | "GRANDMASTER";
  key: string;
  name: string;
  outputKey: string;
  outputName: string;
  category: "CONSUMABLE" | "EQUIPMENT";
  subType: string;
  icon: string;
  equipSlot?: "WEAPON" | "ARMOR" | "BOOTS" | "RING" | "TALISMAN" | "ARTIFACT";
  description: string;
  usage: string;
  ingredients: SeedIngredient[];
  fee: number;
  minutes: number;
  exp: number;
  modifiers?: Record<string, unknown>;
};

const A = "alchemy" as const;
const F = "forging" as const;
const T = "talisman" as const;
const M = "formation" as const;

const R = (
  profession: SeedProfessionRecipe["profession"],
  station: SeedProfessionRecipe["station"],
  rank: SeedProfessionRecipe["rank"],
  key: string,
  name: string,
  outputKey: string,
  outputName: string,
  category: SeedProfessionRecipe["category"],
  subType: string,
  icon: string,
  description: string,
  usage: string,
  ingredients: SeedIngredient[],
  fee: number,
  minutes: number,
  exp: number,
  extra: Partial<Pick<SeedProfessionRecipe, "equipSlot" | "modifiers">> = {}
): SeedProfessionRecipe => ({ profession, station, rank, key, name, outputKey, outputName, category, subType, icon, description, usage, ingredients, fee, minutes, exp, ...extra });

export const coreProfessionRecipes: SeedProfessionRecipe[] = [
  R(A, "ALCHEMY_FURNACE", "APPRENTICE", "recipe-tu-khi-dan", "Luyện Tụ Khí Đan", "tu-khi-dan", "Tụ Khí Đan", "CONSUMABLE", "Đan Dược", "pill", "Đan dược hạ phẩm giúp tích lũy tu vi giai đoạn đầu.", "Sử dụng để nhận một lượng nhỏ Tu Vi.", [{ key: "thanh-linh-thao", name: "Thanh Linh Thảo", qty: 2, icon: "herb" }, { key: "linh-tuyen-thuy", name: "Linh Tuyền Thủy", qty: 1, icon: "water" }], 80, 10, 20, { modifiers: { cultivation: 40 } }),
  R(A, "ALCHEMY_FURNACE", "APPRENTICE", "recipe-hoi-khi-dan", "Luyện Hồi Khí Đan", "hoi-khi-dan", "Hồi Khí Đan", "CONSUMABLE", "Đan Dược", "pill", "Đan dược hạ phẩm khôi phục Chân Nguyên.", "Hồi 25% Chân Nguyên tối đa.", [{ key: "hoi-khi-thao", name: "Hồi Khí Thảo", qty: 2, icon: "herb" }, { key: "thanh-linh-thao", name: "Thanh Linh Thảo", qty: 1, icon: "herb" }], 90, 12, 22, { modifiers: { qiRestorePct: 25 } }),
  R(A, "ALCHEMY_FURNACE", "APPRENTICE", "recipe-duong-the-dan", "Luyện Dưỡng Thể Đan", "duong-the-dan", "Dưỡng Thể Đan", "CONSUMABLE", "Đan Dược", "pill", "Ôn dưỡng thân thể, hồi phục sinh lực và thể lực.", "Hồi 20% HP và 20% Thể Lực.", [{ key: "huyet-sam", name: "Huyết Sâm", qty: 1, icon: "root" }, { key: "cuong-than-thao", name: "Cường Thân Thảo", qty: 2, icon: "herb" }], 100, 15, 25, { modifiers: { hpRestorePct: 20, energyRestorePct: 20 } }),
  R(A, "ALCHEMY_FURNACE", "ADEPT", "recipe-ngung-khi-dan", "Luyện Ngưng Khí Đan", "ngung-khi-dan", "Ngưng Khí Đan", "CONSUMABLE", "Đan Dược", "pill", "Đan dược trung phẩm đẩy nhanh tích lũy tu vi.", "Sử dụng để nhận Tu Vi.", [{ key: "thanh-linh-thao", name: "Thanh Linh Thảo", qty: 4, icon: "herb" }, { key: "ngung-khi-hoa", name: "Ngưng Khí Hoa", qty: 2, icon: "flower" }, { key: "linh-tuyen-thuy", name: "Linh Tuyền Thủy", qty: 1, icon: "water" }], 250, 30, 60, { modifiers: { cultivation: 150 } }),
  R(A, "ALCHEMY_FURNACE", "ADEPT", "recipe-hoi-nguyen-dan", "Luyện Hồi Nguyên Đan", "hoi-nguyen-dan", "Hồi Nguyên Đan", "CONSUMABLE", "Đan Dược", "pill", "Đan dược trung phẩm hồi lượng lớn Chân Nguyên.", "Hồi 50% Chân Nguyên tối đa.", [{ key: "hoi-khi-thao", name: "Hồi Khí Thảo", qty: 4, icon: "herb" }, { key: "nguyen-linh-qua", name: "Nguyên Linh Quả", qty: 1, icon: "fruit" }, { key: "linh-tuyen-thuy", name: "Linh Tuyền Thủy", qty: 2, icon: "water" }], 280, 35, 65, { modifiers: { qiRestorePct: 50 } }),
  R(A, "ALCHEMY_FURNACE", "ADEPT", "recipe-thanh-tam-dan", "Luyện Thanh Tâm Đan", "thanh-tam-dan", "Thanh Tâm Đan", "CONSUMABLE", "Đan Dược", "pill", "Ổn định tâm thần, hóa giải trạng thái tinh thần cơ bản.", "Xóa một debuff tinh thần cơ bản khi hệ thống hỗ trợ.", [{ key: "thanh-tam-lien", name: "Thanh Tâm Liên", qty: 2, icon: "flower" }, { key: "ngung-than-thao", name: "Ngưng Thần Thảo", qty: 2, icon: "herb" }, { key: "linh-tuyen-thuy", name: "Linh Tuyền Thủy", qty: 1, icon: "water" }], 320, 40, 70, { modifiers: { cleanseMental: true } }),
  R(A, "ALCHEMY_FURNACE", "EXPERT", "recipe-truc-co-dan", "Luyện Trúc Cơ Đan", "truc-co-dan-thuong", "Trúc Cơ Đan", "CONSUMABLE", "Đan Dược", "pill", "Đan dược hỗ trợ đột phá đại cảnh giới phù hợp.", "Tăng tỷ lệ thành công đột phá.", [{ key: "truc-co-linh-thao", name: "Trúc Cơ Linh Thảo", qty: 3, icon: "herb" }, { key: "ngoc-tuy-chi", name: "Ngọc Tủy Chi", qty: 2, icon: "mushroom" }, { key: "yeu-dan-nhat-giai", name: "Yêu Đan Nhất Giai", qty: 1, icon: "core" }], 1000, 120, 180, { modifiers: { breakthroughBps: 1200 } }),
  R(A, "ALCHEMY_FURNACE", "EXPERT", "recipe-tieu-hoan-dan", "Luyện Tiểu Hoàn Đan", "tieu-hoan-dan", "Tiểu Hoàn Đan", "CONSUMABLE", "Đan Dược", "pill", "Đan dược chữa thương cơ bản nhưng hiệu lực mạnh.", "Hồi 60% HP.", [{ key: "huyet-sam", name: "Huyết Sâm", qty: 4, icon: "root" }, { key: "sinh-co-hoa", name: "Sinh Cơ Hoa", qty: 2, icon: "flower" }, { key: "ngoc-tuy-dich", name: "Ngọc Tủy Dịch", qty: 1, icon: "water" }], 900, 90, 160, { modifiers: { hpRestorePct: 60 } }),
  R(A, "ALCHEMY_FURNACE", "EXPERT", "recipe-tu-than-dan", "Luyện Tụ Thần Đan", "tu-than-dan", "Tụ Thần Đan", "CONSUMABLE", "Đan Dược", "pill", "Đan dược tạm tăng Thần Thức.", "Tăng 10% Spirit trong thời gian ngắn khi buff mở.", [{ key: "ngung-than-thao", name: "Ngưng Thần Thảo", qty: 4, icon: "herb" }, { key: "hon-hoa", name: "Hồn Hoa", qty: 2, icon: "flower" }, { key: "linh-tuyen-tinh-hoa", name: "Linh Tuyền Tinh Hoa", qty: 1, icon: "water" }], 1100, 120, 190, { modifiers: { spiritBps: 1000 } }),
  R(A, "ALCHEMY_FURNACE", "MASTER", "recipe-dai-hoan-dan", "Luyện Đại Hoàn Đan", "dai-hoan-dan", "Đại Hoàn Đan", "CONSUMABLE", "Đan Dược", "pill", "Đan dược hồi phục cực mạnh sau chiến đấu.", "Hồi 90% HP.", [{ key: "thien-nien-huyet-sam", name: "Thiên Niên Huyết Sâm", qty: 1, icon: "root" }, { key: "sinh-menh-linh-chi", name: "Sinh Mệnh Linh Chi", qty: 2, icon: "mushroom" }, { key: "ngoc-tuy", name: "Ngọc Tủy", qty: 2, icon: "gem" }], 3500, 360, 450, { modifiers: { hpRestorePct: 90 } }),
  R(A, "ALCHEMY_FURNACE", "MASTER", "recipe-pha-canh-dan", "Luyện Phá Cảnh Đan", "pha-canh-dan", "Phá Cảnh Đan", "CONSUMABLE", "Đan Dược", "pill", "Đan dược hỗ trợ vượt bình cảnh.", "Tăng bonus đột phá cảnh giới.", [{ key: "pha-canh-hoa", name: "Phá Cảnh Hoa", qty: 2, icon: "flower" }, { key: "thien-linh-qua", name: "Thiên Linh Quả", qty: 2, icon: "fruit" }, { key: "yeu-dan-nhi-giai", name: "Yêu Đan Nhị Giai", qty: 1, icon: "core" }], 5000, 480, 550, { modifiers: { breakthroughBps: 1800 } }),
  R(A, "ALCHEMY_FURNACE", "MASTER", "recipe-tay-tuy-dan", "Luyện Tẩy Tủy Đan", "tay-tuy-dan", "Tẩy Tủy Đan", "CONSUMABLE", "Đan Dược", "pill", "Đan dược tẩy luyện căn cơ.", "Vật phẩm progression cho hệ tẩy luyện sau này.", [{ key: "tay-tuy-linh-dich", name: "Tẩy Tủy Linh Dịch", qty: 2, icon: "water" }, { key: "long-huyet-thao", name: "Long Huyết Thảo", qty: 1, icon: "herb" }, { key: "thien-nien-linh-chi", name: "Thiên Niên Linh Chi", qty: 1, icon: "mushroom" }], 6000, 720, 650, { modifiers: { foundationCleanse: true } }),
  R(A, "ALCHEMY_FURNACE", "GRANDMASTER", "recipe-cuu-chuyen-hoan-hon-dan", "Luyện Cửu Chuyển Hoàn Hồn Đan", "cuu-chuyen-hoan-hon-dan", "Cửu Chuyển Hoàn Hồn Đan", "CONSUMABLE", "Đan Dược", "pill", "Cực phẩm hồi phục dùng trong cảnh giới cao.", "Hồi phục cực mạnh khi hệ cao cấp mở.", [{ key: "hoan-hon-thao", name: "Hoàn Hồn Thảo", qty: 3, icon: "herb" }, { key: "van-nien-linh-chi", name: "Vạn Niên Linh Chi", qty: 1, icon: "mushroom" }, { key: "hon-tinh", name: "Hồn Tinh", qty: 2, icon: "crystal" }, { key: "thien-linh-dich", name: "Thiên Linh Dịch", qty: 2, icon: "water" }], 20000, 1440, 1500, { modifiers: { reviveGrade: 1 } }),
  R(A, "ALCHEMY_FURNACE", "GRANDMASTER", "recipe-ngo-dao-dan", "Luyện Ngộ Đạo Đan", "ngo-dao-dan", "Ngộ Đạo Đan", "CONSUMABLE", "Đan Dược", "pill", "Đan dược hỗ trợ lĩnh ngộ và tu luyện.", "Hỗ trợ lĩnh ngộ công pháp sau này.", [{ key: "ngo-dao-tra-diep", name: "Ngộ Đạo Trà Diệp", qty: 3, icon: "leaf" }, { key: "thien-tam-qua", name: "Thiên Tâm Quả", qty: 2, icon: "fruit" }, { key: "dao-van-tinh-hoa", name: "Đạo Vận Tinh Hoa", qty: 1, icon: "crystal" }], 25000, 1440, 1800, { modifiers: { insightBps: 2000 } }),
  R(A, "ALCHEMY_FURNACE", "GRANDMASTER", "recipe-doat-thien-dan", "Luyện Đoạt Thiên Đan", "doat-thien-dan", "Đoạt Thiên Đan", "CONSUMABLE", "Đan Dược", "pill", "Đan dược Đại Sư dùng cho progression cấp cao.", "Vật phẩm progression cấp cao.", [{ key: "thien-menh-hoa", name: "Thiên Mệnh Hoa", qty: 1, icon: "flower" }, { key: "long-huyet-tinh-hoa", name: "Long Huyết Tinh Hoa", qty: 2, icon: "crystal" }, { key: "van-nien-linh-duoc", name: "Vạn Niên Linh Dược", qty: 3, icon: "herb" }, { key: "dao-van-tinh-hoa", name: "Đạo Vận Tinh Hoa", qty: 2, icon: "crystal" }], 40000, 2880, 2500, { modifiers: { fateGrade: 1 } }),

  R(F, "FORGE", "APPRENTICE", "recipe-thanh-phong-kiem", "Rèn Thanh Phong Kiếm", "thanh-phong-kiem", "Thanh Phong Kiếm", "EQUIPMENT", "Kiếm", "sword", "Kiếm hạ phẩm nhẹ và sắc.", "Trang bị tăng Attack và Speed.", [{ key: "hac-thiet", name: "Hắc Thiết", qty: 4, icon: "ore" }, { key: "thanh-dong", name: "Thanh Đồng", qty: 2, icon: "ore" }], 150, 20, 25, { equipSlot: "WEAPON", modifiers: { attack: 8, speed: 2 } }),
  R(F, "FORGE", "APPRENTICE", "recipe-hac-thiet-giap", "Rèn Hắc Thiết Giáp", "hac-thiet-giap", "Hắc Thiết Giáp", "EQUIPMENT", "Giáp", "armor", "Giáp hạ phẩm bằng hắc thiết.", "Trang bị tăng Defense và HP.", [{ key: "hac-thiet", name: "Hắc Thiết", qty: 6, icon: "ore" }, { key: "thu-bi", name: "Thú Bì", qty: 2, icon: "hide" }], 180, 25, 30, { equipSlot: "ARMOR", modifiers: { defense: 10, maxHp: 20 } }),
  R(F, "FORGE", "APPRENTICE", "recipe-tu-linh-boi", "Rèn Tụ Linh Bội", "tu-linh-boi", "Tụ Linh Bội", "EQUIPMENT", "Pháp khí", "talisman", "Pháp khí phụ trợ tích tụ linh khí.", "Trang bị tăng Spirit và Chân Nguyên.", [{ key: "linh-ngoc-tho", name: "Linh Ngọc Thô", qty: 2, icon: "gem" }, { key: "thanh-dong", name: "Thanh Đồng", qty: 2, icon: "ore" }], 200, 30, 35, { equipSlot: "TALISMAN", modifiers: { spirit: 5, maxQiBps: 500 } }),
  R(F, "FORGE", "ADEPT", "recipe-xich-viem-kiem", "Rèn Xích Viêm Kiếm", "xich-viem-kiem", "Xích Viêm Kiếm", "EQUIPMENT", "Kiếm", "sword", "Kiếm trung phẩm mang hỏa khí.", "Trang bị tăng Attack.", [{ key: "xich-viem-thiet", name: "Xích Viêm Thiết", qty: 4, icon: "ore" }, { key: "hoa-tinh-thach", name: "Hỏa Tinh Thạch", qty: 2, icon: "crystal" }], 500, 60, 75, { equipSlot: "WEAPON", modifiers: { attack: 20, fireDamageBps: 500 } }),
  R(F, "FORGE", "ADEPT", "recipe-thanh-linh-giap", "Rèn Thanh Linh Giáp", "thanh-linh-giap", "Thanh Linh Giáp", "EQUIPMENT", "Giáp", "armor", "Giáp trung phẩm mềm nhẹ.", "Trang bị tăng Defense và HP.", [{ key: "thanh-linh-thiet", name: "Thanh Linh Thiết", qty: 6, icon: "ore" }, { key: "linh-tam-ti", name: "Linh Tằm Ti", qty: 3, icon: "silk" }], 550, 75, 80, { equipSlot: "ARMOR", modifiers: { defense: 22, maxHp: 50 } }),
  R(F, "FORGE", "ADEPT", "recipe-truy-phong-ngoa", "Rèn Truy Phong Ngoa", "truy-phong-ngoa", "Truy Phong Ngoa", "EQUIPMENT", "Giày", "boots", "Giày trung phẩm có phong linh.", "Trang bị tăng Speed.", [{ key: "phong-linh-thach", name: "Phong Linh Thạch", qty: 2, icon: "crystal" }, { key: "yeu-thu-bi", name: "Yêu Thú Bì", qty: 4, icon: "hide" }], 480, 60, 70, { equipSlot: "BOOTS", modifiers: { speed: 15 } }),
  R(F, "FORGE", "EXPERT", "recipe-tu-dien-kiem", "Rèn Tử Điện Kiếm", "tu-dien-kiem", "Tử Điện Kiếm", "EQUIPMENT", "Kiếm", "sword", "Kiếm thượng phẩm dẫn lôi.", "Trang bị tăng Attack và Speed.", [{ key: "loi-tinh-thiet", name: "Lôi Tinh Thiết", qty: 4, icon: "ore" }, { key: "tu-dien-tinh-thach", name: "Tử Điện Tinh Thạch", qty: 2, icon: "crystal" }, { key: "yeu-dan-nhat-giai", name: "Yêu Đan Nhất Giai", qty: 1, icon: "core" }], 1800, 180, 220, { equipSlot: "WEAPON", modifiers: { attack: 45, speed: 10 } }),
  R(F, "FORGE", "EXPERT", "recipe-huyen-giap", "Rèn Huyền Giáp", "huyen-giap", "Huyền Giáp", "EQUIPMENT", "Giáp", "armor", "Giáp thượng phẩm nặng và bền.", "Trang bị tăng Defense và HP.", [{ key: "huyen-thiet", name: "Huyền Thiết", qty: 8, icon: "ore" }, { key: "huyen-quy-giap-phien", name: "Huyền Quy Giáp Phiến", qty: 2, icon: "shell" }], 2000, 240, 250, { equipSlot: "ARMOR", modifiers: { defense: 55, maxHp: 100 } }),
  R(F, "FORGE", "EXPERT", "recipe-tu-linh-gioi", "Rèn Tụ Linh Giới", "tu-linh-gioi", "Tụ Linh Giới", "EQUIPMENT", "Nhẫn", "ring", "Nhẫn thượng phẩm tụ linh.", "Trang bị tăng Spirit và Chân Nguyên.", [{ key: "linh-ngoc", name: "Linh Ngọc", qty: 3, icon: "gem" }, { key: "khong-minh-thach", name: "Không Minh Thạch", qty: 1, icon: "crystal" }], 2200, 240, 260, { equipSlot: "RING", modifiers: { spirit: 15, maxQiBps: 1000 } }),
  R(F, "FORGE", "MASTER", "recipe-thien-cuong-kiem", "Rèn Thiên Cương Kiếm", "thien-cuong-kiem", "Thiên Cương Kiếm", "EQUIPMENT", "Kiếm", "sword", "Kiếm cực phẩm cứng như thiên cương.", "Trang bị tăng Attack mạnh.", [{ key: "thien-ngoai-huyen-thiet", name: "Thiên Ngoại Huyền Thiết", qty: 3, icon: "ore" }, { key: "kiem-tam-thach", name: "Kiếm Tâm Thạch", qty: 2, icon: "crystal" }, { key: "yeu-dan-nhi-giai", name: "Yêu Đan Nhị Giai", qty: 1, icon: "core" }], 8000, 720, 700, { equipSlot: "WEAPON", modifiers: { attack: 90, speed: 12 } }),
  R(F, "FORGE", "MASTER", "recipe-long-lan-giap", "Rèn Long Lân Giáp", "long-lan-giap", "Long Lân Giáp", "EQUIPMENT", "Giáp", "armor", "Giáp cực phẩm dùng long lân.", "Trang bị tăng Defense và HP mạnh.", [{ key: "long-lan-phien", name: "Long Lân Phiến", qty: 3, icon: "scale" }, { key: "thien-ngoai-huyen-thiet", name: "Thiên Ngoại Huyền Thiết", qty: 4, icon: "ore" }, { key: "linh-tam-ti", name: "Linh Tằm Ti", qty: 5, icon: "silk" }], 10000, 960, 850, { equipSlot: "ARMOR", modifiers: { defense: 110, maxHp: 220 } }),
  R(F, "FORGE", "MASTER", "recipe-can-khon-gioi", "Rèn Càn Khôn Giới", "can-khon-gioi", "Càn Khôn Giới", "EQUIPMENT", "Nhẫn", "ring", "Nhẫn cực phẩm chứa không gian.", "Trang bị tăng Spirit, sau này hỗ trợ túi đồ.", [{ key: "khong-minh-thach", name: "Không Minh Thạch", qty: 3, icon: "crystal" }, { key: "khong-gian-tinh-thach", name: "Không Gian Tinh Thạch", qty: 1, icon: "crystal" }, { key: "linh-ngoc-cuc-pham", name: "Linh Ngọc Cực Phẩm", qty: 2, icon: "gem" }], 12000, 1080, 950, { equipSlot: "RING", modifiers: { spirit: 35, maxQiBps: 1800 } }),
  R(F, "FORGE", "GRANDMASTER", "recipe-tru-ta-kiem", "Rèn Tru Tà Kiếm", "tru-ta-kiem", "Tru Tà Kiếm", "EQUIPMENT", "Kiếm", "sword", "Kiếm tiên phẩm trấn tà.", "Trang bị tăng Attack cực mạnh.", [{ key: "thai-at-tinh-kim", name: "Thái Ất Tinh Kim", qty: 3, icon: "ore" }, { key: "kiem-hon", name: "Kiếm Hồn", qty: 1, icon: "spirit" }, { key: "thien-loi-tinh", name: "Thiên Lôi Tinh", qty: 2, icon: "crystal" }], 35000, 2880, 2200, { equipSlot: "WEAPON", modifiers: { attack: 180, speed: 25 } }),
  R(F, "FORGE", "GRANDMASTER", "recipe-hon-nguyen-dao-bao", "Rèn Hỗn Nguyên Đạo Bào", "hon-nguyen-dao-bao", "Hỗn Nguyên Đạo Bào", "EQUIPMENT", "Đạo bào", "armor", "Đạo bào tiên phẩm hộ thân.", "Trang bị tăng Defense, HP và Spirit.", [{ key: "thien-tam-than-ti", name: "Thiên Tằm Thần Ti", qty: 5, icon: "silk" }, { key: "hon-nguyen-linh-tinh", name: "Hỗn Nguyên Linh Tinh", qty: 2, icon: "crystal" }, { key: "van-nien-yeu-bi", name: "Vạn Niên Yêu Bì", qty: 2, icon: "hide" }], 40000, 2880, 2500, { equipSlot: "ARMOR", modifiers: { defense: 180, maxHp: 400, spirit: 40 } }),
  R(F, "FORGE", "GRANDMASTER", "recipe-hu-khong-an", "Rèn Hư Không Ấn", "hu-khong-an", "Hư Không Ấn", "EQUIPMENT", "Pháp bảo", "artifact", "Pháp bảo tiên phẩm điều động không gian.", "Trang bị tăng Spirit và hiệu ứng không gian sau này.", [{ key: "khong-gian-tinh-hach", name: "Không Gian Tinh Hạch", qty: 2, icon: "crystal" }, { key: "thai-at-tinh-kim", name: "Thái Ất Tinh Kim", qty: 4, icon: "ore" }, { key: "dao-van-thach", name: "Đạo Văn Thạch", qty: 3, icon: "stone" }], 60000, 4320, 3200, { equipSlot: "ARTIFACT", modifiers: { spirit: 90, maxQiBps: 3000 } }),

  R(T, "TALISMAN_TABLE", "APPRENTICE", "recipe-hoa-cau-phu", "Chế Hỏa Cầu Phù", "hoa-cau-phu", "Hỏa Cầu Phù", "CONSUMABLE", "Phù Lục", "scroll", "Phù hạ phẩm ngưng hỏa cầu.", "Gây sát thương Hỏa cơ bản khi hệ chiến đấu hỗ trợ.", [{ key: "hoang-phu-chi", name: "Hoàng Phù Chỉ", qty: 1, icon: "paper" }, { key: "chu-sa", name: "Chu Sa", qty: 1, icon: "powder" }, { key: "hoa-linh-phan", name: "Hỏa Linh Phấn", qty: 1, icon: "powder" }], 60, 8, 18, { modifiers: { fireDamage: 30 } }),
  R(T, "TALISMAN_TABLE", "APPRENTICE", "recipe-ho-than-phu", "Chế Hộ Thân Phù", "ho-than-phu", "Hộ Thân Phù", "CONSUMABLE", "Phù Lục", "scroll", "Phù hạ phẩm tạo hộ thuẫn nhỏ.", "Tạo shield nhỏ.", [{ key: "hoang-phu-chi", name: "Hoàng Phù Chỉ", qty: 1, icon: "paper" }, { key: "chu-sa", name: "Chu Sa", qty: 2, icon: "powder" }], 70, 10, 20, { modifiers: { shield: 40 } }),
  R(T, "TALISMAN_TABLE", "APPRENTICE", "recipe-tat-hanh-phu", "Chế Tật Hành Phù", "tat-hanh-phu", "Tật Hành Phù", "CONSUMABLE", "Phù Lục", "scroll", "Phù hạ phẩm tăng tốc.", "Tăng Speed tạm thời.", [{ key: "hoang-phu-chi", name: "Hoàng Phù Chỉ", qty: 1, icon: "paper" }, { key: "phong-linh-phan", name: "Phong Linh Phấn", qty: 2, icon: "powder" }], 80, 12, 22, { modifiers: { speedBps: 800 } }),
  R(T, "TALISMAN_TABLE", "ADEPT", "recipe-bao-viem-phu", "Chế Bạo Viêm Phù", "bao-viem-phu", "Bạo Viêm Phù", "CONSUMABLE", "Phù Lục", "scroll", "Phù trung phẩm bộc phát hỏa diễm.", "Gây sát thương Hỏa mạnh hơn.", [{ key: "linh-phu-chi", name: "Linh Phù Chỉ", qty: 1, icon: "paper" }, { key: "hoa-tinh-phan", name: "Hỏa Tinh Phấn", qty: 2, icon: "powder" }, { key: "chu-sa", name: "Chu Sa", qty: 2, icon: "powder" }], 220, 25, 55, { modifiers: { fireDamage: 90 } }),
  R(T, "TALISMAN_TABLE", "ADEPT", "recipe-kim-cuong-phu", "Chế Kim Cương Phù", "kim-cuong-phu", "Kim Cương Phù", "CONSUMABLE", "Phù Lục", "scroll", "Phù trung phẩm tăng phòng ngự.", "Tăng Defense tạm thời.", [{ key: "linh-phu-chi", name: "Linh Phù Chỉ", qty: 1, icon: "paper" }, { key: "kim-linh-phan", name: "Kim Linh Phấn", qty: 2, icon: "powder" }, { key: "chu-sa", name: "Chu Sa", qty: 2, icon: "powder" }], 250, 30, 60, { modifiers: { defenseBps: 1000 } }),
  R(T, "TALISMAN_TABLE", "ADEPT", "recipe-tich-ta-phu", "Chế Tịch Tà Phù", "tich-ta-phu", "Tịch Tà Phù", "CONSUMABLE", "Phù Lục", "scroll", "Phù trung phẩm kháng tà khí.", "Kháng debuff tà khí/tinh thần.", [{ key: "linh-phu-chi", name: "Linh Phù Chỉ", qty: 1, icon: "paper" }, { key: "thanh-tam-moc-phan", name: "Thanh Tâm Mộc Phấn", qty: 1, icon: "powder" }, { key: "chu-sa", name: "Chu Sa", qty: 3, icon: "powder" }], 280, 35, 65, { modifiers: { resistEvilBps: 1000 } }),
  R(T, "TALISMAN_TABLE", "EXPERT", "recipe-thien-loi-phu", "Chế Thiên Lôi Phù", "thien-loi-phu", "Thiên Lôi Phù", "CONSUMABLE", "Phù Lục", "scroll", "Phù thượng phẩm dẫn thiên lôi.", "Gây sát thương Lôi.", [{ key: "huyen-phu-chi", name: "Huyền Phù Chỉ", qty: 1, icon: "paper" }, { key: "loi-tinh-phan", name: "Lôi Tinh Phấn", qty: 3, icon: "powder" }, { key: "yeu-huyet", name: "Yêu Huyết", qty: 1, icon: "blood" }], 900, 90, 180, { modifiers: { lightningDamage: 180 } }),
  R(T, "TALISMAN_TABLE", "EXPERT", "recipe-don-dia-phu", "Chế Độn Địa Phù", "don-dia-phu", "Độn Địa Phù", "CONSUMABLE", "Phù Lục", "scroll", "Phù thượng phẩm hỗ trợ thoát hiểm.", "Dùng cho travel/escape khi world hỗ trợ.", [{ key: "huyen-phu-chi", name: "Huyền Phù Chỉ", qty: 1, icon: "paper" }, { key: "tho-linh-tinh", name: "Thổ Linh Tinh", qty: 2, icon: "crystal" }, { key: "khong-minh-phan", name: "Không Minh Phấn", qty: 1, icon: "powder" }], 1100, 120, 210, { modifiers: { escapeGrade: 1 } }),
  R(T, "TALISMAN_TABLE", "EXPERT", "recipe-phong-cam-phu", "Chế Phong Cấm Phù", "phong-cam-phu", "Phong Cấm Phù", "CONSUMABLE", "Phù Lục", "scroll", "Phù thượng phẩm phong tỏa hành động.", "Debuff Speed hoặc khóa hành động ngắn.", [{ key: "huyen-phu-chi", name: "Huyền Phù Chỉ", qty: 2, icon: "paper" }, { key: "phong-linh-tinh", name: "Phong Linh Tinh", qty: 2, icon: "crystal" }, { key: "chu-sa-tinh", name: "Chu Sa Tinh", qty: 2, icon: "powder" }], 1200, 120, 230, { modifiers: { bindBps: 1000 } }),
  R(T, "TALISMAN_TABLE", "MASTER", "recipe-ngu-loi-phu", "Chế Ngũ Lôi Phù", "ngu-loi-phu", "Ngũ Lôi Phù", "CONSUMABLE", "Phù Lục", "scroll", "Phù cực phẩm gọi ngũ lôi.", "Gây sát thương Lôi mạnh.", [{ key: "thien-phu-chi", name: "Thiên Phù Chỉ", qty: 1, icon: "paper" }, { key: "ngu-hanh-loi-tinh", name: "Ngũ Hành Lôi Tinh", qty: 3, icon: "crystal" }, { key: "yeu-dan-nhi-giai", name: "Yêu Đan Nhị Giai", qty: 1, icon: "core" }], 4500, 480, 580, { modifiers: { lightningDamage: 500 } }),
  R(T, "TALISMAN_TABLE", "MASTER", "recipe-ho-menh-phu", "Chế Hộ Mệnh Phù", "ho-menh-phu", "Hộ Mệnh Phù", "CONSUMABLE", "Phù Lục", "scroll", "Phù cực phẩm cứu nguy.", "Khi HP thấp tạo shield lớn sau này.", [{ key: "thien-phu-chi", name: "Thiên Phù Chỉ", qty: 2, icon: "paper" }, { key: "sinh-menh-tinh-hoa", name: "Sinh Mệnh Tinh Hoa", qty: 2, icon: "crystal" }, { key: "chu-sa-cuc-pham", name: "Chu Sa Cực Phẩm", qty: 2, icon: "powder" }], 5500, 600, 650, { modifiers: { shield: 500 } }),
  R(T, "TALISMAN_TABLE", "MASTER", "recipe-pha-cam-phu", "Chế Phá Cấm Phù", "pha-cam-phu", "Phá Cấm Phù", "CONSUMABLE", "Phù Lục", "scroll", "Phù cực phẩm phá cấm chế.", "Dùng trong quest/ruins/trận pháp sau này.", [{ key: "thien-phu-chi", name: "Thiên Phù Chỉ", qty: 2, icon: "paper" }, { key: "pha-cam-thach-phan", name: "Phá Cấm Thạch Phấn", qty: 3, icon: "powder" }, { key: "khong-minh-tinh", name: "Không Minh Tinh", qty: 1, icon: "crystal" }], 6000, 720, 700, { modifiers: { breakSealGrade: 1 } }),
  R(T, "TALISMAN_TABLE", "GRANDMASTER", "recipe-thai-hu-loi-phu", "Chế Thái Hư Lôi Phù", "thai-hu-loi-phu", "Thái Hư Lôi Phù", "CONSUMABLE", "Phù Lục", "scroll", "Phù tiên phẩm hàm chứa thái hư lôi.", "Gây sát thương Lôi cấp cao.", [{ key: "tien-phu-chi", name: "Tiên Phù Chỉ", qty: 1, icon: "paper" }, { key: "thai-hu-loi-tinh", name: "Thái Hư Lôi Tinh", qty: 2, icon: "crystal" }, { key: "loi-hon", name: "Lôi Hồn", qty: 1, icon: "spirit" }], 20000, 1440, 1600, { modifiers: { lightningDamage: 1200 } }),
  R(T, "TALISMAN_TABLE", "GRANDMASTER", "recipe-can-khon-na-di-phu", "Chế Càn Khôn Na Di Phù", "can-khon-na-di-phu", "Càn Khôn Na Di Phù", "CONSUMABLE", "Phù Lục", "scroll", "Phù tiên phẩm na di không gian.", "Dịch chuyển đặc biệt khi world hỗ trợ.", [{ key: "tien-phu-chi", name: "Tiên Phù Chỉ", qty: 2, icon: "paper" }, { key: "khong-gian-tinh-hach", name: "Không Gian Tinh Hạch", qty: 1, icon: "crystal" }, { key: "dao-van-tinh-hoa", name: "Đạo Văn Tinh Hoa", qty: 2, icon: "crystal" }], 25000, 1440, 1900, { modifiers: { teleportGrade: 1 } }),
  R(T, "TALISMAN_TABLE", "GRANDMASTER", "recipe-van-pha-ho-than-phu", "Chế Vạn Phá Hộ Thân Phù", "van-pha-ho-than-phu", "Vạn Phá Hộ Thân Phù", "CONSUMABLE", "Phù Lục", "scroll", "Phù tiên phẩm hộ thân toàn diện.", "Tạo phòng hộ cấp cao.", [{ key: "tien-phu-chi", name: "Tiên Phù Chỉ", qty: 2, icon: "paper" }, { key: "ngu-hanh-tinh-hoa", name: "Ngũ Hành Tinh Hoa", qty: 5, icon: "crystal" }, { key: "dao-van-tinh-hoa", name: "Đạo Văn Tinh Hoa", qty: 2, icon: "crystal" }], 35000, 2880, 2400, { modifiers: { shield: 1600 } }),

  R(M, "FORMATION_ALTAR", "APPRENTICE", "recipe-tu-linh-tran", "Lập Tụ Linh Trận", "tu-linh-tran", "Tụ Linh Trận", "CONSUMABLE", "Trận Bàn", "formation", "Trận hạ phẩm tụ linh khí.", "Tăng nhẹ hiệu quả tu luyện tại khu vực sau này.", [{ key: "ha-pham-tran-ky", name: "Hạ Phẩm Trận Kỳ", qty: 4, icon: "flag" }, { key: "linh-thach", name: "Linh Thạch", qty: 20, icon: "crystal" }, { key: "tran-van-mac", name: "Trận Văn Mặc", qty: 1, icon: "ink" }], 150, 20, 25, { modifiers: { cultivationBps: 300 } }),
  R(M, "FORMATION_ALTAR", "APPRENTICE", "recipe-canh-gioi-tran", "Lập Cảnh Giới Trận", "canh-gioi-tran", "Cảnh Giới Trận", "CONSUMABLE", "Trận Bàn", "formation", "Trận hạ phẩm cảnh báo biến động.", "Cảnh báo kẻ địch/sự kiện khi gameplay hỗ trợ.", [{ key: "ha-pham-tran-ky", name: "Hạ Phẩm Trận Kỳ", qty: 4, icon: "flag" }, { key: "linh-moc", name: "Linh Mộc", qty: 2, icon: "wood" }, { key: "tran-van-mac", name: "Trận Văn Mặc", qty: 1, icon: "ink" }], 160, 25, 28, { modifiers: { warningGrade: 1 } }),
  R(M, "FORMATION_ALTAR", "APPRENTICE", "recipe-tieu-ho-tran", "Lập Tiểu Hộ Trận", "tieu-ho-tran", "Tiểu Hộ Trận", "CONSUMABLE", "Trận Bàn", "formation", "Trận hạ phẩm phòng hộ nhỏ.", "Bonus Defense trong khu vực.", [{ key: "ha-pham-tran-ky", name: "Hạ Phẩm Trận Kỳ", qty: 6, icon: "flag" }, { key: "hac-thiet", name: "Hắc Thiết", qty: 2, icon: "ore" }, { key: "linh-thach", name: "Linh Thạch", qty: 30, icon: "crystal" }], 200, 30, 32, { modifiers: { defenseBps: 500 } }),
  R(M, "FORMATION_ALTAR", "ADEPT", "recipe-liet-hoa-tran", "Lập Liệt Hỏa Trận", "liet-hoa-tran", "Liệt Hỏa Trận", "CONSUMABLE", "Trận Bàn", "formation", "Trận trung phẩm hỏa sát.", "Tạo sát trận Hỏa khi hệ trận mở.", [{ key: "trung-pham-tran-ky", name: "Trung Phẩm Trận Kỳ", qty: 6, icon: "flag" }, { key: "hoa-tinh-thach", name: "Hỏa Tinh Thạch", qty: 3, icon: "crystal" }, { key: "hoa-linh-mac", name: "Hỏa Linh Mặc", qty: 2, icon: "ink" }], 600, 60, 80, { modifiers: { fireDamage: 180 } }),
  R(M, "FORMATION_ALTAR", "ADEPT", "recipe-me-vu-tran", "Lập Mê Vụ Trận", "me-vu-tran", "Mê Vụ Trận", "CONSUMABLE", "Trận Bàn", "formation", "Trận trung phẩm tạo mê vụ.", "Giảm accuracy/speed hoặc dùng trong encounter.", [{ key: "trung-pham-tran-ky", name: "Trung Phẩm Trận Kỳ", qty: 6, icon: "flag" }, { key: "huyen-vu-hoa", name: "Huyễn Vụ Hoa", qty: 3, icon: "flower" }, { key: "hon-sa", name: "Hồn Sa", qty: 1, icon: "sand" }], 650, 75, 90, { modifiers: { speedDebuffBps: 800 } }),
  R(M, "FORMATION_ALTAR", "ADEPT", "recipe-tu-nguyen-tran", "Lập Tụ Nguyên Trận", "tu-nguyen-tran", "Tụ Nguyên Trận", "CONSUMABLE", "Trận Bàn", "formation", "Trận trung phẩm tụ nguyên khí.", "Tăng hồi phục Chân Nguyên / hiệu suất tu luyện.", [{ key: "trung-pham-tran-ky", name: "Trung Phẩm Trận Kỳ", qty: 8, icon: "flag" }, { key: "linh-tinh", name: "Linh Tinh", qty: 3, icon: "crystal" }, { key: "nguyen-linh-thach", name: "Nguyên Linh Thạch", qty: 2, icon: "crystal" }], 750, 90, 100, { modifiers: { qiRegenBps: 800 } }),
  R(M, "FORMATION_ALTAR", "EXPERT", "recipe-bat-mon-khon-tran", "Lập Bát Môn Khốn Trận", "bat-mon-khon-tran", "Bát Môn Khốn Trận", "CONSUMABLE", "Trận Bàn", "formation", "Trận thượng phẩm khống chế mục tiêu.", "Khống chế mục tiêu/khu vực.", [{ key: "huyen-pham-tran-ky", name: "Huyền Phẩm Trận Kỳ", qty: 8, icon: "flag" }, { key: "khong-minh-thach", name: "Không Minh Thạch", qty: 2, icon: "crystal" }, { key: "tran-van-tinh", name: "Trận Văn Tinh", qty: 3, icon: "crystal" }], 2500, 240, 260, { modifiers: { bindBps: 1500 } }),
  R(M, "FORMATION_ALTAR", "EXPERT", "recipe-ngu-hanh-sat-tran", "Lập Ngũ Hành Sát Trận", "ngu-hanh-sat-tran", "Ngũ Hành Sát Trận", "CONSUMABLE", "Trận Bàn", "formation", "Trận thượng phẩm vận ngũ hành sát khí.", "Sát trận ngũ hành.", [{ key: "huyen-pham-tran-ky", name: "Huyền Phẩm Trận Kỳ", qty: 10, icon: "flag" }, { key: "kim-linh-tinh", name: "Kim Linh Tinh", qty: 1, icon: "crystal" }, { key: "moc-linh-tinh", name: "Mộc Linh Tinh", qty: 1, icon: "crystal" }, { key: "thuy-linh-tinh", name: "Thủy Linh Tinh", qty: 1, icon: "crystal" }, { key: "hoa-linh-tinh", name: "Hỏa Linh Tinh", qty: 1, icon: "crystal" }, { key: "tho-linh-tinh", name: "Thổ Linh Tinh", qty: 1, icon: "crystal" }], 3000, 300, 300, { modifiers: { elementalDamage: 360 } }),
  R(M, "FORMATION_ALTAR", "EXPERT", "recipe-ho-son-tran", "Lập Hộ Sơn Trận", "ho-son-tran", "Hộ Sơn Trận", "CONSUMABLE", "Trận Bàn", "formation", "Trận thượng phẩm phòng hộ sơn môn.", "Defensive formation cấp trung.", [{ key: "huyen-pham-tran-ky", name: "Huyền Phẩm Trận Kỳ", qty: 12, icon: "flag" }, { key: "huyen-thiet", name: "Huyền Thiết", qty: 4, icon: "ore" }, { key: "linh-tinh", name: "Linh Tinh", qty: 5, icon: "crystal" }], 3500, 360, 340, { modifiers: { defenseBps: 1800 } }),
  R(M, "FORMATION_ALTAR", "MASTER", "recipe-cuu-cung-phong-toa-tran", "Lập Cửu Cung Phong Tỏa Trận", "cuu-cung-phong-toa-tran", "Cửu Cung Phong Tỏa Trận", "CONSUMABLE", "Trận Bàn", "formation", "Trận cực phẩm phong tỏa không gian.", "Phong tỏa khu vực.", [{ key: "thien-pham-tran-ky", name: "Thiên Phẩm Trận Kỳ", qty: 9, icon: "flag" }, { key: "khong-gian-tinh-thach", name: "Không Gian Tinh Thạch", qty: 3, icon: "crystal" }, { key: "tran-tam-thach", name: "Trận Tâm Thạch", qty: 1, icon: "stone" }], 10000, 960, 800, { modifiers: { bindBps: 3000 } }),
  R(M, "FORMATION_ALTAR", "MASTER", "recipe-van-kiem-sat-tran", "Lập Vạn Kiếm Sát Trận", "van-kiem-sat-tran", "Vạn Kiếm Sát Trận", "CONSUMABLE", "Trận Bàn", "formation", "Trận cực phẩm sát phạt bằng kiếm khí.", "Sát trận mạnh.", [{ key: "thien-pham-tran-ky", name: "Thiên Phẩm Trận Kỳ", qty: 12, icon: "flag" }, { key: "kiem-tinh", name: "Kiếm Tinh", qty: 5, icon: "crystal" }, { key: "kiem-hon", name: "Kiếm Hồn", qty: 1, icon: "spirit" }, { key: "tran-tam-thach", name: "Trận Tâm Thạch", qty: 1, icon: "stone" }], 12000, 1200, 950, { modifiers: { swordDamage: 900 } }),
  R(M, "FORMATION_ALTAR", "MASTER", "recipe-thien-dia-tu-linh-dai-tran", "Lập Thiên Địa Tụ Linh Đại Trận", "thien-dia-tu-linh-dai-tran", "Thiên Địa Tụ Linh Đại Trận", "CONSUMABLE", "Trận Bàn", "formation", "Đại trận cực phẩm tụ linh.", "Tăng mạnh hiệu suất tu luyện tại khu vực.", [{ key: "thien-pham-tran-ky", name: "Thiên Phẩm Trận Kỳ", qty: 12, icon: "flag" }, { key: "thien-linh-tinh", name: "Thiên Linh Tinh", qty: 5, icon: "crystal" }, { key: "dia-mach-tinh-hoa", name: "Địa Mạch Tinh Hoa", qty: 2, icon: "crystal" }], 15000, 1440, 1100, { modifiers: { cultivationBps: 2500 } }),
  R(M, "FORMATION_ALTAR", "GRANDMASTER", "recipe-chu-thien-tinh-dau-tran", "Lập Chu Thiên Tinh Đấu Trận", "chu-thien-tinh-dau-tran", "Chu Thiên Tinh Đấu Trận", "CONSUMABLE", "Trận Bàn", "formation", "Trận tiên phẩm dẫn tinh thần lực.", "Đại trận cấp cao.", [{ key: "tien-pham-tran-ky", name: "Tiên Phẩm Trận Kỳ", qty: 12, icon: "flag" }, { key: "tinh-than-thach", name: "Tinh Thần Thạch", qty: 7, icon: "crystal" }, { key: "tinh-hon", name: "Tinh Hồn", qty: 2, icon: "spirit" }], 45000, 4320, 2800, { modifiers: { starPower: 1 } }),
  R(M, "FORMATION_ALTAR", "GRANDMASTER", "recipe-hon-nguyen-phong-thien-tran", "Lập Hỗn Nguyên Phong Thiên Trận", "hon-nguyen-phong-thien-tran", "Hỗn Nguyên Phong Thiên Trận", "CONSUMABLE", "Trận Bàn", "formation", "Trận tiên phẩm phong thiên địa.", "Phong tỏa cấp đại trận.", [{ key: "tien-pham-tran-ky", name: "Tiên Phẩm Trận Kỳ", qty: 16, icon: "flag" }, { key: "hon-nguyen-tinh", name: "Hỗn Nguyên Tinh", qty: 4, icon: "crystal" }, { key: "khong-gian-tinh-hach", name: "Không Gian Tinh Hạch", qty: 2, icon: "crystal" }, { key: "dao-van-tinh-hoa", name: "Đạo Văn Tinh Hoa", qty: 2, icon: "crystal" }], 60000, 5760, 3500, { modifiers: { sealHeaven: 1 } }),
  R(M, "FORMATION_ALTAR", "GRANDMASTER", "recipe-van-tien-dai-tran", "Lập Vạn Tiên Đại Trận", "van-tien-dai-tran", "Vạn Tiên Đại Trận", "CONSUMABLE", "Trận Bàn", "formation", "Đại trận tiên phẩm tối thượng.", "Đại trận progression cấp cao.", [{ key: "tien-pham-tran-ky", name: "Tiên Phẩm Trận Kỳ", qty: 20, icon: "flag" }, { key: "ngu-hanh-tinh-hoa", name: "Ngũ Hành Tinh Hoa", qty: 10, icon: "crystal" }, { key: "dao-van-tinh-hoa", name: "Đạo Văn Tinh Hoa", qty: 5, icon: "crystal" }, { key: "tran-dao-chan-tinh", name: "Trận Đạo Chân Tinh", qty: 1, icon: "crystal" }], 100000, 10080, 5000, { modifiers: { immortalFormation: 1 } })
];
